import { IProject } from '../types/Project'

export const projectList: IProject[] = [
	{
		name: 'Ally',
		repo: 'https://github.com/kailahk/hackathon',
		app: 'https://ally-5t5u.onrender.com/',
		description:
			'A relationship management tool that leverages AI to provide users with resources catered to their situation',
		tech: [
			'React',
			'JavaScript',
			'React-Datepicker',
			'Node.js',
			'Express',
			'MongoDB',
			'Mongoose',
			'NoSQL',
			'Passport',
			'JWT',
			'bcrypt',
			'OpenAI',
			'Figma',
		],
	},
	{
		name: 'TalkThru',
		repo: 'https://github.com/PeterSYoo/talkthru-frontend',
		app: 'https://talkthru.netlify.app/',
		description:
			'A SaaS video-chat platform that connects users on a peer-to-peer level to collaborate on shared interests in real-time',
		tech: [
			'React',
			'TypeScript',
			'Vite',
			'Tailwind CSS',
			'PeerJS',
			'Socket.io',
			'Zod',
			'Node.js',
			'Express',
			'SQL',
			'PlanetScale',
			'Prisma',
			'Jira',
			'Figma',
		],
	},
	{
		name: '@tkg808/Trie-Search',
		repo: 'https://github.com/tkg808/trie-search',
		app: 'https://www.npmjs.com/package/@tkg808/trie-search',
		description:
			'A flexible implementation of a trie data structure that efficiently finds partial and complete matches',
		tech: ['Node.js', 'TypeScript', 'Jest'],
	},
	{
		name: 'FitKick',
		repo: 'https://github.com/tkg808/fitkick-ui',
		app: 'https://fitkick.netlify.app/',
		description:
			'A community-driven fitness web application where users can create customizable exercises and workout routines',
		tech: [
			'React',
			'JavaScript',
			'Django',
			'DRF',
			'Python',
			'PostgreSQL',
			'SQL',
			'Bootstrap',
			'React-Big-Calendar',
			'Date.fns',
		],
	},
	{
		name: 'Nutrition Tracker',
		repo: 'https://github.com/tkg808/nutrition-tracker',
		app: 'https://nutrition-tracker.netlify.app/',
		description:
			'A macro-friendly, nutrition-based web application that allows users to track their progress toward dietary goals',
		tech: [
			'React',
			'JavaScript',
			'Node.js',
			'Express',
			'MongoDB',
			'NoSQL',
			'Mongoose',
			'Passport',
			'JWT',
			'bcrypt',
			'Axios',
			'Chart.js',
		],
	},
]
